Turn off LTO for 32 bit liblog as a workaround
With global ThinLTO, building anything that depends on arm32 or x86
liblog fails with the following error:

ld.lld: error: out/soong/.intermediates/system/logging/liblog/liblog/android_arm_armv8-a_shared/liblog.so: undefined reference to __aeabi_uldivmod@LIBC_PRIVATE [--no-allow-shlib-undefined]

Test: GLOBAL_THINLTO=true m
Bug: 241259844
Change-Id: I6eb81fa49f3f575820f148b44dee77a03d7fa521